# Generated by Django 3.0.8 on 2021-08-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0002_nameinpersonalinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nameinpersonalinfo',
        ),
    ]
