# Generated by Django 3.0.8 on 2021-08-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0003_delete_nameinpersonalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='nameinpersonalinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField()),
                ('title', models.CharField(max_length=5)),
                ('firstname', models.TextField()),
                ('middlename', models.TextField()),
                ('lastname', models.TextField()),
                ('email', models.CharField(max_length=40)),
                ('dob', models.DateField()),
                ('placeofbirth', models.CharField(max_length=50)),
            ],
        ),
    ]
