# Generated by Django 3.0.8 on 2021-08-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0004_nameinpersonalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameinpersonalinfo',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
