# Generated by Django 3.0.8 on 2021-08-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0005_auto_20210817_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailinpersonalinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField()),
                ('email', models.CharField(max_length=40)),
                ('emailtype', models.CharField(max_length=20)),
                ('nameoftheemail', models.TextField()),
            ],
        ),
    ]
