# Generated by Django 3.0.8 on 2021-08-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0006_emailinpersonalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='phoneinpersonalinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField()),
                ('pcountry', models.TextField()),
                ('phonenumber', models.TextField()),
                ('nickname', models.TextField()),
                ('phonetype', models.TextField()),
            ],
        ),
    ]
