# Generated by Django 3.0.8 on 2021-08-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0007_phoneinpersonalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='addressinpersonalinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField()),
                ('country', models.TextField()),
                ('State', models.TextField()),
                ('city', models.TextField()),
                ('address', models.TextField()),
                ('street', models.TextField()),
                ('pincode', models.TextField()),
                ('nameofaddress', models.TextField()),
            ],
        ),
    ]
