# Generated by Django 3.0.8 on 2021-08-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0008_addressinpersonalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='companyinpersonalinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField()),
                ('companyname', models.TextField()),
                ('jobtitle', models.TextField()),
            ],
        ),
    ]
