# Generated by Django 3.0.8 on 2021-08-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0014_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='taxnumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField()),
                ('taxno', models.TextField()),
                ('taxname', models.TextField()),
            ],
        ),
    ]
