# Generated by Django 3.0.8 on 2021-08-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0016_extensionuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionuser',
            name='salt',
            field=models.TextField(),
        ),
    ]
