# Generated by Django 3.0.8 on 2021-08-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0017_auto_20210818_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='extensionuser',
        ),
    ]
