# Generated by Django 3.0.8 on 2021-08-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0024_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='password',
        ),
    ]
