# Generated by Django 3.0.8 on 2021-08-18 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0026_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitehandler.extensionuser'),
        ),
    ]
