# Generated by Django 3.0.8 on 2021-08-18 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0028_auto_20210818_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='password',
        ),
    ]
