# Generated by Django 3.0.8 on 2021-08-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0031_remove_password_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='password',
        ),
    ]
