# Generated by Django 3.0.8 on 2021-08-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0033_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='extensionuser',
        ),
    ]
