# Generated by Django 3.1.4 on 2021-08-21 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0036_extensionuser_randomkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extensionuser',
            name='randomkey',
        ),
    ]
